### ISSUE TITLE
Release image

### ISSUE THREAD

**Issue by susumutomita** [knocks-public/2024-CircuitBreaker#58]
![IMG_1796](https://github.com/knocks-public/2024-CircuitBreaker/assets/11481781/07acd052-e339-42ef-af42-5ade29bbb44d)
![IMG_1801](https://github.com/knocks-public/2024-CircuitBreaker/assets/11481781/a206a30f-10d0-449d-ab0b-2c36418a4cc3)
![IMG_1802](https://github.com/knocks-public/2024-CircuitBreaker/assets/11481781/f4ed5c7f-f307-49a9-b303-683fa63bbf32)
![IMG_1803](https://github.com/knocks-public/2024-CircuitBreaker/assets/11481781/205c84f8-bf78-4ff4-b82a-c95f4c33315a)
![IMG_1804](https://github.com/knocks-public/2024-CircuitBreaker/assets/11481781/82ff0a74-725d-4f60-9402-dc950c29244d)
![IMG_1805](https://github.com/knocks-public/2024-CircuitBreaker/assets/11481781/40e9b3fa-e5ec-4df1-82cf-e8f08c69a350)

**Comment by sakuyacatcat** [comment]
![inro-architecture](https://github.com/knocks-public/2024-CircuitBreaker/assets/66736869/bad68dd0-5f02-418d-92b7-1ea06867dfb1)
